#! /usr/bin/env bash

# =================================================================
#
# Work of the U.S. Department of Defense, Defense Digital Service.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

if ! command -v terraform > /dev/null; then
  echo "terraform is missing."
  exit 1
fi

terraform fmt "${DIR}/.."
