#!/bin/bash

# =================================================================
#
# Work of the U.S. Department of Defense, Defense Digital Service.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
set -eu

# move up a directory
cd $DIR/..

pkgs=$(go list ./... | grep -v /vendor/ | tr "\n" " ")

echo "******************"
echo "Running go vet"
go vet $pkgs
echo "******************"
echo "Running go vet with shadow"
go vet -vettool="bin/shadow" $pkgs
echo "******************"
echo "Running errcheck"
bin/errcheck ${pkgs}
echo "******************"
echo "Running ineffassign"
bin/ineffassign ./test
echo "******************"
echo "Running staticcheck"
bin/staticcheck -checks all ${pkgs}
