#! /usr/bin/env bash

# =================================================================
#
# Work of the U.S. Department of Defense, Defense Digital Service.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

set -eu -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

if ! command -v go > /dev/null; then
  echo "go is missing."
  exit 1
fi

if ! command -v terraform > /dev/null; then
  echo "terraform is missing."
  exit 1
fi

go test -short -count 1 -timeout 15m "${DIR}/../test/..."
