#!/bin/bash

set -eu -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

if ! command -v terraform-docs > /dev/null; then
  echo "terraform-docs is missing."
  exit 1
fi

pushd "${DIR}/.." > /dev/null
terraform-docs markdown . > README.md
echo "<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
cat README.md >> TMP_README.md
echo "<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
mv TMP_README.md README.md
popd  > /dev/null
